# Generated by Django 5.0.1 on 2024-01-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedrooms', models.FloatField()),
                ('bathrooms', models.FloatField()),
                ('land_size', models.FloatField()),
                ('furnished', models.CharField(choices=[('no', 'no'), ('yes', 'yes')], max_length=5)),
                ('province', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('sector', models.CharField(max_length=50)),
                ('prediction', models.FloatField()),
            ],
        ),
    ]
