# Generated by Django 5.0.1 on 2024-01-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0002_alter_predresults_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredResultSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(max_length=50)),
                ('bedrooms', models.FloatField()),
                ('bathrooms', models.FloatField()),
                ('province', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('sector', models.CharField(max_length=50)),
                ('area', models.FloatField()),
                ('prediction', models.FloatField()),
            ],
        ),
    ]
